services:
  db:
    image: mysql:8.0
    container_name: duizendrovers-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: 1000rovers
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

  api:
    build: .
    container_name: duizendrovers-api
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: 1000rovers
      DB_CONN_LIMIT: 10
      CORS_ORIGIN: http://localhost:5173,http://localhost:3001
    ports:
      - "3000:3000"
    command: ["node", "dist/server.js"]

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
